version: "3.9"

networks:
  algafood-network:
    driver: bridge
    
services:
  algafood-mysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3316:3316"
    networks:
      - algafood-network
      
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3316", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      S3-ID-KEY-ACCESS: ${S3-ID-KEY-ACCESS}
      S3-KEY-SECRET: ${S3-KEY-SECRET}
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
    networks:
        - algafood-network
    depends_on:
        - algafood-mysql 
        
        
  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network
      
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
      
     